name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install the dependencies
        run: >
          pacman -Syu --noconfirm --needed
          cmake extra-cmake-modules dbus
          qt6-base qt6-declarative
          kcmutils ki18n kirigami ksvg kwindowsystem
          libplasma plasma-workspace plasma5support

      - uses: actions/checkout@v7

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
          cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure
